#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# only username, user id and Home directory path for the user are displayed

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
