#!/usr/bin/env bash
# get Apache to run on the container 
# and return a page containing Hello Holberton

sudo apt-get update
sudo apt-get install –y apache2
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf
sudo service apache2 start
